---
- name: Ensure registry config path is available
  file:
    dest: "{{ registry_dict.config_path }}"
    state: directory
  tags:
    - init

- name: Ensure registry cert path is available
  file:
    dest: "{{ registry_dict.cert_path }}"
    state: directory
  tags:
    - init

- name: Ensure registry role path is available
  file:
    dest: "{{ registry_dict.role_path }}"
    state: directory
  tags:
    - init

- name: Ensure registry data path is available
  file:
    dest: "{{ registry_dict.data_path }}"
    state: directory
  tags:
    - init

- name: Generate an OpenSSL private key
  openssl_privatekey:
    path: "{{ registry_dict.cert_path }}/registry.key"
    type: RSA
    size: 4096

- name: Generate an OpenSSL Certificate Signing Request
  openssl_csr:
    path: "{{ registry_dict.cert_path }}/registry.csr"
    privatekey_path: "{{ registry_dict.cert_path }}/registry.key"
    common_name: registry

- name: Generate a Self Signed OpenSSL certificate
  openssl_certificate:
    path: "{{ registry_dict.cert_path }}/registry.crt"
    privatekey_path: "{{ registry_dict.cert_path }}/registry.key"
    csr_path: "{{ registry_dict.cert_path }}/registry.csr"
    provider: selfsigned

- name: Add a user to the password file and ensure permissions are set
  htpasswd:
    path: "{{ registry_dict.data_path }}/htpasswd"
    name: gitlab
    password: "thispasswdneedtobechanged"
    owner: root
    group: root
    mode: 0640

- name: Ensure registry configuration file is updated
  template:
    backup: yes
    src: "registry-config.yml.j2"
    dest: "{{ registry_dict.config_path }}/config.yml"
    mode: "0644"

- name: Ensure registry compose file is updated
  template:
    backup: yes
    src: "docker-compose.yml.j2"
    dest: "{{ registry_dict.role_path }}/docker-compose.yml"
    mode: "0644"