---
- name: Ensure registry config path is available
  file:
    dest: "{{ registry_dict.config_path }}"
    state: directory
  tags:
    - init

- name: Ensure registry cert path is available
  file:
    dest: "{{ registry_dict.cert_path }}"
    state: directory
  tags:
    - init

- name: Ensure registry role path is available
  file:
    dest: "{{ registry_dict.role_path }}"
    state: directory
  tags:
    - init

- name: Ensure registry data path is available
  file:
    dest: "{{ registry_dict.data_path }}"
    state: directory
  tags:
    - init

- name: Ensure registry configuration file is updated
  template:
    backup: yes
    src: "registry-config.yml.j2"
    dest: "{{ registry_dict.config_path }}/config.yml"
    mode: "0644"

- name: Ensure registry compose file is updated
  template:
    backup: yes
    src: "docker-compose.yml.j2"
    dest: "{{ registry_dict.role_path }}/docker-compose.yml"
    mode: "0644"