---
username: 'voc'

directories:
  - "/home/{{ username }}/gitlab"
  - "/home/{{ username }}/gitlab/config"
  - "/home/{{ username }}/gitlab/logs"
  - "/home/{{ username }}/gitlab/data"
  - "/home/{{ username }}/gitlab-runner"
  - "/home/{{ username }}/gitlab-runner/config"


repo_url: "https://github.com/remipichon/voc.git"
repo_version: "HEAD"

