---
username: 'voc'

directories:
  - "/home/{{ username }}/gitlab"
  - "/home/{{ username }}/gitlab/config"
  - "/home/{{ username }}/gitlab/logs"
  - "/home/{{ username }}/gitlab/data"
  - "/home/{{ username }}/gitlab-runner"
  - "/home/{{ username }}/gitlab-runner/config"

main_dir: "/home/{{ username }}/voc/core/"


repo_url: "https://github.com/remipichon/voc.git"
repo_version: "HEAD"


docker_compose_version: "1.15.0"

