version: '3'

services:
  gitlab:
    networks: 
      - network
    image: 'gitlab/gitlab-ce:latest'
    container_name: 'gitlab'
    ports:
      - '80:80'
      - '443:443'
      - '22:22'
    volumes:
      - '~/gitlab/config:/etc/gitlab'
      - '~/srv/gitlab/logs:/var/log/gitlab'
      - '~/srv/gitlab/data:/var/opt/gitlab'

  host_docker_runner:
    networks: 
      - network
    image: 'gitlab/gitlab-runner:latest'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '~/srv/gitlab-runner/config:/etc/gitlab-runner'

networks:
  network:

