version: '3'

services:
  mailin:
    networks: 
      - mail
    image: 'mailin:1.0'
    build:
      context: mailin
    ports:
      - '25:25'
    environment:
      - MAIL_WEBHOOK=voc_mailin_mediation:80/mediation
    depends_on:
      - mailin_mediation
  mailin_mediation:
      networks:
        - mail
      image: 'mailin-mediation:1.0'
      build:
        context: mailin-mediation
      ports:
        - '3100:80'
      environment:
        - AUTHORIZED_MAIL_HOST=mail.remip.eu
        - DEBUG=true
      #  - TEST_WEBHOOK=test-mail-webhook:80

networks:
  mail: