FROM docker:latest

RUN apk update; apk add git; apk add --update nodejs nodejs-npm && npm install npm@latest -g

# copy node app code
COPY app/package.json /root/app/package.json
RUN cd /root/app/; npm install;
COPY app /root/app/
