version: '3.2'

services:
  remote_docker_runner:
    networks:
      - network
    image: 'gitlab/gitlab-runner:latest'
    depends_on:
      - gitlab
    volumes:
      - 'remoterunnerconfig:/etc/gitlab-runner'

  node_remote_docker:
     image: 'vocproject/runnerappremote'
     deploy:
       replicas: 0
     build:
       context: .
       dockerfile: Dockerfile.runner-app-remote


volumes:
  remoterunnerconfig: