before_script:
   - docker info

dockerstuff:
 stage: build
 script:
   - mkdir -p /builds/tool_user/portainer_config/job-result/ #currently there is a bug in voc runner app
   - cd $CI_PROJECT_DIR; node /root/app/app.js
 tags:
   - voc_docker_host
 artifacts:
   when: always
   expire_in: 1 week
   paths:
    - job-result/result.json

variables:
 GIT_STRATEGY: fetch
