---
gitlab_root_path: "/data/athena/gitlab"

in_gitlab_dict:
  name: gitlab
  image:
    name: gitlab/gitlab-ce
    version: 9.2.6-ce.0
  uid: 998
  gid: 998
  http_port: 80
  https_port: 443
  git_port: 2222
  role_path: "{{ gitlab_root_path }}/role/"
  data_path: "{{ gitlab_root_path }}/data/"
  config_path: "{{ gitlab_root_path }}/config/"
  log_path: "{{ gitlab_root_path }}/log/"
  healthcheck:
    retries: 10
  db:
    deploy_postgresql: true
    image:
      name: "{{ athena_registry }}/athena/postgresql"
      version: 9.5
    hostname: postgresql
    port: 5432
    data_path: "{{ gitlab_root_path }}/postgresql"
    name: gitlab
    user: gitlab
    password: "s3cR3t"
  deploy:
    networks: []
    mode: 'default'
    compose_version: '3'
    delegate_to: "{{ inventory_hostname }}"
    force_pull: no
  configuration:
    external_url: http://localhost
    ssh_host: localhost
    time_zone: "Europe/Paris"
    download_path: /var/opt/gitlab/tmp/repositories
    backup:
      enable: true
      path: /var/opt/gitlab/backups
      keep_time: 604800
      cron_schedule: "0 5 * * *"
    trusted_proxies: "localhost"
    enable_https: false
    enable_prometheus: false
    smtp:
      enabled: False
      port: 465
      starttls: true
      tls: false
      ssl_verify_mode: 'none'
      email_from: 'example@example.com'
      email_display_name: 'Example'
      email_reply_to: 'noreply@example.com'
  environment:
    GITLAB_ROOT_PASSWORD: "5uP325eC23t"
    http_proxy: "{{ proxy_env.http_proxy | default('') }}"
    https_proxy: "{{ proxy_env.https_proxy | default('') }}"
    no_proxy: "{{ proxy_env.no_proxy | default('') }}"