---
#- name: Get key server
#  apt_key:
#    keyserver: https://download.docker.com/linux/ubuntu/gpg
#    id: ???
#    state: present

- name: Add docker.list to sources.list
  lineinfile:
    dest: "/etc/apt/sources.list.d/docker.list"
    line: "{{item}}"
    create: yes
  with_items:
    - "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic edge"

- name: Update repositories
  apt:
    update_cache: "yes"

- name: Install packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ package }}"

- name:
  pip:
    name: docker-compose
    version: "{{ docker_compose_version }}"
    state: present

- name: Add user mod
  user:
    name: "{{ username }}"
    group: docker

#- name: Install Docker Compose
#  get_url:
#    url: "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-{{ ansible_system }}-{{ ansible_architecture }}"
#    dest: "/usr/local/bin/docker-compose"
#    mode: 0755