---
- name: Get key server
  apt_key:
    keyserver: hkp://p80.pool.sks-keyservers.net:80
    id: 58118E89F3A912897C070ADBF76221572C52609D
    state: present

- name: Add docker.list to sources.list
  lineinfile:
    dest: "/etc/apt/sources.list.d/docker.list"
    line: "{{item}}"
    create: yes
  with_items:
    - "deb https://apt.dockerproject.org/repo ubuntu-{{ ansible_distribution_release }} main"

- name: Update repositories
  apt:
    update_cache: "yes"

- name: Install packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ package }}"

- name:
  pip:
    name: docker-compose
    version: 1.9.0
    state: present

- name: Add user mod
  user:
    name: "{{ username }}"
    group: docker

- name: Install Docker Compose
  get_url:
    url: "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-{{ ansible_system }}-{{ ansible_architecture }}"
    dest: "/usr/local/bin/docker-compose"
    mode: 0755