---
- hosts: all
  become: yes
  tasks:
    - name: Make sure we have a 'wheel' group
      group:
        name: wheel
        state: present

    - name: Allow 'wheel' group to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: "^%wheel"
        line: "%wheel ALL=(ALL) NOPASSWD: ALL"
        validate: visudo -cf %s

    - name: Add user ansible to wheel group
      user:
        name: "ansible"
        groups: wheel
        shell: "/bin/bash"
        append: yes

    - name: Add your public key to authorized key of ansible
      authorized_key:
        user: ansible
        state: present
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"