---
- name: Installing Docker | Get key server
  command: apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D

- name: Installing Docker | add deb repo
  file:
    path: "/etc/apt/sources.list.d/docker.list"
    state: touch

- name: Installing Docker | get the code name of the currently installed distribution
  command: lsb_release -cs
  register: codename

- name: Installing Docker | add docker.list to sources.list
  lineinfile:
    dest: "/etc/apt/sources.list.d/docker.list"
    line: "{{item}}"
  with_items:
    - "deb https://apt.dockerproject.org/repo ubuntu-{{ codename.stdout }} main"

- name: Installing Docker | apt update
  apt:
    update_cache: "yes"

- name: Installing Docker | install docker-engine
  apt:
    name: docker-engine
    state: present

- name: Installing Docker | add user mod
  user:
    name: "{{ username }}"
    group: docker