version: "3"

services:
  redis:
    image: redis:3.2-alpine
    ports:
      - "6379"
    networks:
      - voteapp
    deploy:
      replicas: 2
      placement:
        constraints: [node.role == manager]
  db_pouet:
    image: postgres:9.4
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - voteapp
    deploy:
      placement:
        constraints: [node.role == manager]


networks:
    voteapp:

volumes:
  db-data: