---
- name: Check if 'hostname' var is defined
  fail:
    msg: "You need to define '-e hostname= ' See https://github.com/remipichon/voc/blob/master/Installation.md#gitlab"
  when: hostname is undefined

  # how to fetch the tokent from the password ?

- name: Check if 'runner_token' var is defined
  fail:
    msg: "You need to define '-e runner_token= ' See /admin/runners"
  when: runner_token is undefined

- name: Register host docker runner id
  register: host_docker_runner_id
  command: "docker ps -q --filter \"name=voc_host_docker_runner\""


- name: "register"
  command: "docker exec -t {{ host_docker_runner_id.stdout }} gitlab-runner register --non-interactive --name {{ name }} --url {{url}} --registration-token {{token}} --executor docker --docker-tlsverify=false --docker-pull-policy if-not-present --docker-image {{image}} --docker-privileged true --docker-disable-cache false --docker-volumes {{volumes}}"

- name: "sed volume"
  command: "docker exec -t {{ host_docker_runner_id.stdout }} sed -i \"/volumes/c\    volumes = [\\\"/cache\\\",\\\"{{volumes}}\\\"]\" /etc/gitlab-runner/config.toml"


#Go to <your_gitlab>/admin/runners/ to add _node_host_docker_ tag and use it in your gitlab-ci.yml file.

